### ISSUE TITLE
Getting authentication failure

### ISSUE THREAD

**Issue by harisf3** [navisens/iOS-app-helloworld#1]
Getting following exception, same devkey is working in android

<img width="466" alt="Screenshot 2020-09-24 at 5 08 58 PM" src="https://user-images.githubusercontent.com/43817946/94143061-bbeb7880-fe88-11ea-8d11-24ef0e6335fb.png">

**Comment by jamesgrantham** [comment]
Hi Harisf3. What version of the SDK are you using? 1.9.6 is the most recent release and should not have this issue. If you are not specifying a SDK version in your podfile then `pod update` should bring you to the latest version.
